CREATE TABLE likes (
	person_id INTEGER,
	beer_id INTEGER,
	PRIMARY KEY (person_id, beer_id),
	FOREIGN KEY (person_id) REFERENCES people(id),
	FOREIGN KEY (beer_id) REFERENCES beers(id)
);

INSERT INTO likes(person_id, beer_id)
VALUES
       ( 1,  4),
       ( 1,  6),
       ( 1,  9),
       ( 1, 10),
       ( 2,  2),
       ( 2,  4),
       ( 2,  6),
       ( 2,  7),
       ( 2,  8),
       ( 2, 10),
       ( 3,  1),
       ( 3,  4),
       ( 3,  6),
       ( 3,  8),
       ( 3, 10),
       ( 4,  1),
       ( 4,  2),
       ( 4,  3),
       ( 4,  4),
       ( 4,  8),
       ( 4,  9),
       ( 4, 10),
       ( 5,  1),
       ( 5,  3),
       ( 5,  4),
       ( 5,  6),
       ( 5,  8),
       ( 5,  9),
       ( 6,  1),
       ( 6,  2),
       ( 6,  5),
       ( 7,  1),
       ( 7,  2),
       ( 7,  4),
       ( 7,  5),
       ( 7,  6),
       ( 7,  7),
       ( 7,  8),
       ( 7,  9),
       ( 7, 10),
       ( 8,  1),
       ( 9,  3);
